"""SQLAlchemy models. Generated by Backend Agent."""
from datetime import datetime, date
from typing import Optional, Any
from uuid import UUID, uuid4
from sqlalchemy import Column, String, Integer, Numeric, Boolean, DateTime, Date, JSON, ForeignKey
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship, DeclarativeBase


class Base(DeclarativeBase):
    pass


class Users(Base):
    """Athlete user accounts"""
    __tablename__ = "users"

    id = Column(PGUUID(as_uuid=True), primary_key=True)
    email = Column(String, unique=True, nullable=False)
    full_name = Column(String, nullable=False)
    sport = Column(String)
    subscription_tier = Column(String)
    stripe_customer_id = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow)


class TrainingSessions(Base):
    """Individual training session records"""
    __tablename__ = "training_sessions"

    id = Column(PGUUID(as_uuid=True), primary_key=True)
    user_id = Column(PGUUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    session_date = Column(Date, nullable=False)
    sport_type = Column(String, nullable=False)
    duration_minutes = Column(Integer)
    intensity = Column(String)
    notes = Column(String)
    metrics = Column(JSON)


class PerformanceMetrics(Base):
    """Athlete performance data points"""
    __tablename__ = "performance_metrics"

    id = Column(PGUUID(as_uuid=True), primary_key=True)
    user_id = Column(PGUUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    metric_type = Column(String, nullable=False)
    value = Column(Numeric, nullable=False)
    unit = Column(String)
    recorded_at = Column(DateTime, default=datetime.utcnow)


class AiInsights(Base):
    """AI-generated training insights"""
    __tablename__ = "ai_insights"

    id = Column(PGUUID(as_uuid=True), primary_key=True)
    user_id = Column(PGUUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    insight_type = Column(String, nullable=False)
    content = Column(String, nullable=False)
    context = Column(JSON)


class Subscriptions(Base):
    """Stripe subscription records"""
    __tablename__ = "subscriptions"

    id = Column(PGUUID(as_uuid=True), primary_key=True)
    user_id = Column(PGUUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    stripe_subscription_id = Column(String, unique=True, nullable=False)
    plan = Column(String, nullable=False)
    status = Column(String, nullable=False)
    current_period_end = Column(DateTime)

