-- Migration: Initial Schema
-- Generated by Backend Agent
-- Supabase-compatible PostgreSQL

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Athlete user accounts
CREATE TABLE IF NOT EXISTS users (
id UUID PRIMARY KEY,
email TEXT UNIQUE NOT NULL,
full_name TEXT NOT NULL,
sport TEXT,
subscription_tier TEXT DEFAULT 'free',
stripe_customer_id TEXT,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);

-- Individual training session records
CREATE TABLE IF NOT EXISTS training_sessions (
id UUID PRIMARY KEY,
user_id UUID REFERENCES users(id) NOT NULL,
session_date DATE NOT NULL,
sport_type TEXT NOT NULL,
duration_minutes INTEGER,
intensity TEXT,
notes TEXT,
metrics JSONB DEFAULT '{}'
);

-- Athlete performance data points
CREATE TABLE IF NOT EXISTS performance_metrics (
id UUID PRIMARY KEY,
user_id UUID REFERENCES users(id) NOT NULL,
metric_type TEXT NOT NULL,
value NUMERIC NOT NULL,
unit TEXT,
recorded_at TIMESTAMP DEFAULT NOW()
);

-- AI-generated training insights
CREATE TABLE IF NOT EXISTS ai_insights (
id UUID PRIMARY KEY,
user_id UUID REFERENCES users(id) NOT NULL,
insight_type TEXT NOT NULL,
content TEXT NOT NULL,
context JSONB DEFAULT '{}'
);

-- Stripe subscription records
CREATE TABLE IF NOT EXISTS subscriptions (
id UUID PRIMARY KEY,
user_id UUID REFERENCES users(id) NOT NULL,
stripe_subscription_id TEXT UNIQUE NOT NULL,
plan TEXT NOT NULL,
status TEXT NOT NULL,
current_period_end TIMESTAMP
);

-- Enable Row Level Security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE training_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE performance_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

-- RLS Policy for training_sessions
CREATE POLICY "Users can view own training_sessions"
    ON training_sessions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own training_sessions"
    ON training_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own training_sessions"
    ON training_sessions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own training_sessions"
    ON training_sessions FOR DELETE USING (auth.uid() = user_id);

-- RLS Policy for performance_metrics
CREATE POLICY "Users can view own performance_metrics"
    ON performance_metrics FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own performance_metrics"
    ON performance_metrics FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own performance_metrics"
    ON performance_metrics FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own performance_metrics"
    ON performance_metrics FOR DELETE USING (auth.uid() = user_id);

-- RLS Policy for ai_insights
CREATE POLICY "Users can view own ai_insights"
    ON ai_insights FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own ai_insights"
    ON ai_insights FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own ai_insights"
    ON ai_insights FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own ai_insights"
    ON ai_insights FOR DELETE USING (auth.uid() = user_id);

-- RLS Policy for subscriptions
CREATE POLICY "Users can view own subscriptions"
    ON subscriptions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own subscriptions"
    ON subscriptions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own subscriptions"
    ON subscriptions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own subscriptions"
    ON subscriptions FOR DELETE USING (auth.uid() = user_id);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_training_sessions_user_id ON training_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_performance_metrics_user_id ON performance_metrics(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_insights_user_id ON ai_insights(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON subscriptions(user_id);