"""Pydantic schemas for request/response validation. Generated by Backend Agent."""
from datetime import datetime, date
from typing import Optional, List, Any
from uuid import UUID
from pydantic import BaseModel, EmailStr, Field


# ==================== Auth ====================
class UserCreate(BaseModel):
    email: EmailStr
    password: str = Field(..., min_length=8)
    full_name: str
    sport: Optional[str] = None

class UserLogin(BaseModel):
    email: EmailStr
    password: str

class TokenResponse(BaseModel):
    access_token: str
    refresh_token: Optional[str] = None
    token_type: str = "bearer"

class UserResponse(BaseModel):
    id: UUID
    email: str
    full_name: str
    sport: Optional[str]
    subscription_tier: str
    class Config:
        from_attributes = True

class UserUpdate(BaseModel):
    full_name: Optional[str] = None
    sport: Optional[str] = None


# ==================== Sessions ====================
class SessionCreate(BaseModel):
    session_date: date
    sport_type: str
    duration_minutes: int = Field(..., gt=0)
    intensity: Optional[str] = None
    notes: Optional[str] = None
    metrics: Optional[dict] = None

class SessionResponse(BaseModel):
    id: UUID
    user_id: UUID
    session_date: date
    sport_type: str
    duration_minutes: int
    intensity: Optional[str]
    notes: Optional[str]
    metrics: Optional[dict]
    created_at: datetime
    class Config:
        from_attributes = True

class SessionListResponse(BaseModel):
    sessions: List[SessionResponse]


# ==================== Metrics ====================
class MetricCreate(BaseModel):
    metric_type: str
    value: float
    unit: Optional[str] = None

class MetricResponse(BaseModel):
    id: UUID
    user_id: UUID
    metric_type: str
    value: float
    unit: Optional[str]
    recorded_at: datetime
    class Config:
        from_attributes = True

class MetricListResponse(BaseModel):
    metrics: List[MetricResponse]


# ==================== Dashboard ====================
class DashboardStatsResponse(BaseModel):
    total_sessions: int
    this_week_sessions: int
    total_training_minutes: int
    recent_metrics: List[MetricResponse]
    performance_trend: str


# ==================== Generic ====================
class SuccessResponse(BaseModel):
    success: bool

class ErrorResponse(BaseModel):
    detail: str


# ==================== Insights (OpenAI) ====================
class InsightRequest(BaseModel):
    insight_type: str = Field(..., pattern="^(training_advice|recovery|nutrition)$")

class InsightResponse(BaseModel):
    id: UUID
    user_id: UUID
    insight_type: str
    content: str
    context: Optional[dict]
    created_at: datetime
    class Config:
        from_attributes = True

class InsightListResponse(BaseModel):
    insights: List[InsightResponse]


# ==================== Billing (Stripe) ====================
class CheckoutRequest(BaseModel):
    plan: str = Field(..., pattern="^(pro|premium)$")

class CheckoutResponse(BaseModel):
    checkout_url: str

class SubscriptionResponse(BaseModel):
    id: UUID
    user_id: UUID
    stripe_subscription_id: str
    plan: str
    status: str
    current_period_end: Optional[datetime]
    class Config:
        from_attributes = True
